version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_voting
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis_voting
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: voting_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: "mongodb://mongo:27017/voting"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379

volumes:
  mongo_data:
